import { Parser } from 'json2csv';

export function exportToShopifyCsv(products) {
  const fields = [
    'Handle',
    'Title',
    'Body (HTML)',
    'Vendor',
    'Type',
    'Tags',
    'Published',
    'Option1 Name',
    'Option1 Value',
    'Option2 Name',
    'Option2 Value',
    'Option3 Name',
    'Option3 Value',
    'Variant SKU',
    'Variant Grams',
    'Variant Inventory Tracker',
    'Variant Inventory Qty',
    'Variant Inventory Policy',
    'Variant Fulfillment Service',
    'Variant Price',
    'Variant Compare At Price',
    'Variant Requires Shipping',
    'Variant Taxable',
    'Variant Barcode',
    'Image Src',
    'Image Position',
    'Image Alt Text',
    'Gift Card',
    'SEO Title',
    'SEO Description',
    'Google Shopping / Google Product Category',
    'Google Shopping / Gender',
    'Google Shopping / Age Group',
    'Google Shopping / MPN',
    'Google Shopping / AdWords Grouping',
    'Google Shopping / AdWords Labels',
    'Google Shopping / Condition',
    'Google Shopping / Custom Product',
    'Google Shopping / Custom Label 0',
    'Google Shopping / Custom Label 1',
    'Google Shopping / Custom Label 2',
    'Google Shopping / Custom Label 3',
    'Google Shopping / Custom Label 4',
    'Variant Image',
    'Variant Weight Unit',
    'Variant Tax Code',
    'Cost per item'
  ];

  const opts = { fields };
  const parser = new Parser(opts);

  // Map your product data to match Shopify's format
  const formattedProducts = products.map(product => ({
    Handle: product.handle || '',
    Title: product.name || '',
    'Body (HTML)': product.description || '',
    Vendor: product.vendor || '',
    Type: product.type || '',
    Tags: product.tags || '',
    Published: product.published || 'TRUE',
    'Option1 Name': 'Title',
    'Option1 Value': product.option1Value || 'Default Title',
    'Option2 Name': product.option2Name || '',
    'Option2 Value': product.option2Value || '',
    'Option3 Name': product.option3Name || '',
    'Option3 Value': product.option3Value || '',
    'Variant SKU': product.sku || '',
    'Variant Grams': product.grams || '',
    'Variant Inventory Tracker': product.inventoryTracker || '',
    'Variant Inventory Qty': product.inventoryQty || '',
    'Variant Inventory Policy': product.inventoryPolicy || 'deny',
    'Variant Fulfillment Service': product.fulfillmentService || 'manual',
    'Variant Price': product.price || '',
    'Variant Compare At Price': product.compareAtPrice || '',
    'Variant Requires Shipping': product.requiresShipping || 'TRUE',
    'Variant Taxable': product.taxable || 'TRUE',
    'Variant Barcode': product.barcode || '',
    'Image Src': product.image || '',
    'Image Position': product.imagePosition || '',
    'Image Alt Text': product.imageAltText || '',
    'Gift Card': product.giftCard || 'FALSE',
    'SEO Title': product.seoTitle || '',
    'SEO Description': product.seoDescription || '',
    'Google Shopping / Google Product Category': product.googleProductCategory || '',
    'Google Shopping / Gender': product.googleGender || '',
    'Google Shopping / Age Group': product.googleAgeGroup || '',
    'Google Shopping / MPN': product.googleMpn || '',
    'Google Shopping / AdWords Grouping': product.googleAdWordsGrouping || '',
    'Google Shopping / AdWords Labels': product.googleAdWordsLabels || '',
    'Google Shopping / Condition': product.googleCondition || 'new',
    'Google Shopping / Custom Product': product.googleCustomProduct || '',
    'Google Shopping / Custom Label 0': product.googleCustomLabel0 || '',
    'Google Shopping / Custom Label 1': product.googleCustomLabel1 || '',
    'Google Shopping / Custom Label 2': product.googleCustomLabel2 || '',
    'Google Shopping / Custom Label 3': product.googleCustomLabel3 || '',
    'Google Shopping / Custom Label 4': product.googleCustomLabel4 || '',
    'Variant Image': product.variantImage || '',
    'Variant Weight Unit': product.variantWeightUnit || 'g',
    'Variant Tax Code': product.variantTaxCode || '',
    'Cost per item': product.costPerItem || ''
  }));

  return parser.parse(formattedProducts);
}
